Tim/support exec query
sufleR/sql_query pull request #7
Opened 2020-06-22 19:16 UTC by timhwang21

Note that the specs ended up being identical to `#execute` because the `PG::Result` gives the same results as `ActiveRecord::Result`. However, `MySql::Result#entries` instead returns an array of arrays and does not allow using column names as keys, which is where `exec_query` helps.

2020-06-30 22:05 UTC, sufleR requested changes

2020-06-30 22:05 UTC, sufleR commented on logfile
> +2020-06-22 14:32:47.377 EDT [92612] LOG:  database system is shut down
please remove logfile.

2020-07-11 20:43 UTC, timhwang21 commented on logfile
> +2020-06-22 14:32:47.377 EDT [92612] LOG:  database system is shut down
Sorry for the delay -- updated

2020-08-03 12:13 UTC, sufleR approved these changes

2020-08-03 12:14 UTC, merged